apiVersion: v1
kind: Pod
metadata:
  name: db-staging
  labels:
    app: db-staging
spec:
  containers:
    - name: db-staging
      image: postgres:13
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: postgres-data-staging
          mountPath: /var/lib/postgresql/data
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/k8s
      envFrom:
        - secretRef:
            name: db-secret-staging
      ports:
        - containerPort: 5432
          name: db-port-staging
  volumes:
    - name: postgres-data-staging
      persistentVolumeClaim:
        claimName: db-pod-pvc-staging
---
apiVersion: v1
kind: Service
metadata:
  name: db-nodeport-staging
spec:
  type: NodePort
  selector:
    app: db-staging
  ports:
  - port: 5432
    targetPort: db-port-staging
