apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pod-pvc-staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage