apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion-app-staging
  labels:
    app: lion-app-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lion-app-staging
  template:
    metadata:
      labels:
        app: lion-app-staging
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: lion-app-staging
        image: browneyed.kr.ncr.ntruss.com/lion-app:0.3.1
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: dj-secret-staging
          - secretRef:
              name: db-secret-staging
          - configMapRef:
              name: dj-config-staging
        ports:
          - containerPort: 8000
            name: lion-port
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lion-loadbalancer-staging
spec:
  type: LoadBalancer
  selector:
    app: lion-app-staging
  ports:
    - port: 80
      targetPort: lion-port