apiVersion: v1
kind: Pod
metadata:
  name: {{ include "lionp.db.fullname" . }}
  labels:
    {{- include "lionp.db.selectorLabels" . | nindent 4 }}
spec:
  containers:
    - name: {{ include "lionp.db.fullname" . }}
      image: postgres:13
      env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/k8s"
      envFrom:
        - secretRef:
            name: {{ include "lionp.db.fullname" . }}
      ports:
        - containerPort: {{ .Values.dbService.port }}
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: {{ include "lionp.db.fullname" . }}
