apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lionp.fullname" . }}
  labels:
    {{- include "lionp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lionp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lionp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "lionp.fullname" . }}
            - secretRef:
                name: {{ include "lionp.fullname" . }}
            - secretRef:
                name: {{ include "lionp.db.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/
              port: http
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health/
              port: http
            initialDelaySeconds: 20