apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lionp.fullname" . }}
data:
  DB_HOST: {{ include "lionp.db.fullname" . }}
  DJANGO_SETTINGS_MODULE: {{ .Values.configMap.django.DJANGO_SETTINGS_MODULE }}