apiVersion: v1
kind: Pod
metadata:
  name: db-prod
  labels:
    app: db-prod
spec:
  containers:
    - name: db-prod
      image: postgres:13
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: postgres-data-prod
          mountPath: /var/lib/postgresql/data
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/k8s
      envFrom:
        - secretRef:
            name: db-secret-prod
      ports:
        - containerPort: 5432
          name: db-port-prod
  volumes:
    - name: postgres-data-prod
      persistentVolumeClaim:
        claimName: db-pod-pvc-prod
---
apiVersion: v1
kind: Service
metadata:
  name: db-nodeport-prod
spec:
  type: NodePort
  selector:
    app: db-prod
  ports:
  - port: 5432
    targetPort: db-port-prod