apiVersion: v1
kind: Pod
metadata:
  name: db-config
  labels:
    app: db
spec:
  containers:
    - name: db-config
      image: postgres:13
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      envFrom:
        - configMapRef:
            name: db-config
      ports:
        - containerPort: 5432
          name: db-port
