apiVersion: v1
kind: Pod
metadata:
  name: lion-app
  labels:
    app: lion-app
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: lion-app
      image: browneyed.kr.ncr.ntruss.com/lion-app:latest
      imagePullPolicy: Always
      envFrom:
        - secretRef:
            name: dj-secret
        - secretRef:
            name: db-secret
        - configMapRef:
            name: dj-config
      ports:
        - containerPort: 8000
          name: lion-port

