apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion-app
  labels:
    app: lion-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lion-app
  template:
    metadata:
      labels:
        app: lion-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: lion-app
        image: browneyed.kr.ncr.ntruss.com/lion-app:0.1.0
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: dj-secret
          - secretRef:
              name: db-secret
          - configMapRef:
              name: dj-config
        ports:
          - containerPort: 8000
            name: lion-port
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lion-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: lion-app
  ports:
    - port: 80
      targetPort: lion-port