apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db
      image: postgres:13
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/k8s
      envFrom:
        - secretRef:
            name: db-secret
      ports:
        - containerPort: 5432
          name: db-port
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: db-pod-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-nodeport
spec:
  type: NodePort
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: db-port