replicaCount: 3

image:
  repository: browneyed.kr.ncr.ntruss.com/lion-app
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
  - name: regcred
nameOverride: ""
fullnameOverride: ""


service:
  type: LoadBalancer
  port: 80

containerPort: 8000

configMap:
  django: "django-configmap"

secret:
  django: "django-secret"