apiVersion: v1
kind: Pod
metadata:
  name: lion-manual
  labels:
    creation_method: manual
spec:
  containers:
    - image: teacherssamko/simple-web:v1
      name: lion-manual
      ports:
        - containerPort: 8000
