apiVersion: v1
kind: ReplicationController
metadata:
  name: lion-rc
spec:
  replicas: 3
  selector:
    app: lion-rc
  template:
    metadata:
      name: lion-rc
      labels:
        app: lion-rc
    spec:
      containers:
        - name: lion-rc
          image: teacherssamko/simple-web:v1
          ports:
            - containerPort: 8000

